// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEE-GcJucjr5Ohl-F_Zu4L4bEvk1EJ-h4',
    appId: '1:974478457623:web:3b7ec9f608d3c4cb649552',
    messagingSenderId: '974478457623',
    projectId: 'fir-flutter-codelab-af774',
    authDomain: 'fir-flutter-codelab-af774.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-af774.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB45PKcfVcCXVpK-wTQzcieyTWNTUqYAZU',
    appId: '1:974478457623:android:2f6685072eb27394649552',
    messagingSenderId: '974478457623',
    projectId: 'fir-flutter-codelab-af774',
    storageBucket: 'fir-flutter-codelab-af774.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB0CK_crVKoTVenlJN2GJE1KsV7__E7BQ',
    appId: '1:974478457623:ios:ec1f66162b1eddc9649552',
    messagingSenderId: '974478457623',
    projectId: 'fir-flutter-codelab-af774',
    storageBucket: 'fir-flutter-codelab-af774.appspot.com',
    iosClientId: '974478457623-nubktgcnmpu2icj5r80o239g8thavsfu.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB0CK_crVKoTVenlJN2GJE1KsV7__E7BQ',
    appId: '1:974478457623:ios:ec1f66162b1eddc9649552',
    messagingSenderId: '974478457623',
    projectId: 'fir-flutter-codelab-af774',
    storageBucket: 'fir-flutter-codelab-af774.appspot.com',
    iosClientId: '974478457623-nubktgcnmpu2icj5r80o239g8thavsfu.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
